// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtPi-gmdNfAdrWJ-oxaE2raz8QmHFW0LQ',
    appId: '1:47804794032:web:962e9e57e30a50852a6775',
    messagingSenderId: '47804794032',
    projectId: 'cogscreen-ec86f',
    authDomain: 'cogscreen-ec86f.firebaseapp.com',
    storageBucket: 'cogscreen-ec86f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdYOXej2w_MviTihviAwf3WY1vwm9Pjoo',
    appId: '1:47804794032:android:701890953f3575c32a6775',
    messagingSenderId: '47804794032',
    projectId: 'cogscreen-ec86f',
    storageBucket: 'cogscreen-ec86f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Ks8rE4t0i38FMQljkZd3Z41m9vIQubs',
    appId: '1:47804794032:ios:33b0d03f369368e62a6775',
    messagingSenderId: '47804794032',
    projectId: 'cogscreen-ec86f',
    storageBucket: 'cogscreen-ec86f.appspot.com',
    iosBundleId: 'com.example.cogScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Ks8rE4t0i38FMQljkZd3Z41m9vIQubs',
    appId: '1:47804794032:ios:fed150f9973180792a6775',
    messagingSenderId: '47804794032',
    projectId: 'cogscreen-ec86f',
    storageBucket: 'cogscreen-ec86f.appspot.com',
    iosBundleId: 'com.example.cogScreen.RunnerTests',
  );
}
